[package]
name = "simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
openblas-src = { version = "0.10.12", features = ["static"] }
ndarray-linalg = { version = "0.17", features = ["openblas-static"] }
plotters = "0.3"
gtk4 = "0.9.7"
plotters-gtk4 = "0.5.0"
